"""
pdf_report.py -- renders a DePatch AI security report (Markdown text
produced by llm_engine, plus the raw GNN findings) into a colorful,
styled PDF.

Uses fpdf2 (pure-Python, no system dependencies like wkhtmltopdf/cairo),
so `pip install fpdf2` is enough on any machine, including WSL.
"""
import os
import re
import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos

NAVY = (30, 41, 82)
PURPLE = (106, 27, 154)
RED = (161, 38, 34)
GREEN = (47, 125, 50)
GRAY = (90, 90, 90)
LIGHT_GRAY = (240, 240, 240)
CODE_BG = (39, 40, 34)      # monokai-ish dark background
CODE_FG = (248, 248, 242)

_UNICODE_REPLACEMENTS = {
    "\u2022": "-", "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
    "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u2192": "->", "\u2190": "<-",
}


def _sanitize(text: str) -> str:
    for uni, ascii_eq in _UNICODE_REPLACEMENTS.items():
        text = text.replace(uni, ascii_eq)
    # Final safety net: core PDF fonts only support latin-1, so silently
    # transliterate anything else rather than ever crashing on unexpected
    # LLM output.
    return text.encode("latin-1", errors="replace").decode("latin-1")


class DePatchPDF(FPDF):
    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, self.w, 18, "F")
        self.set_xy(10, 4)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, "DEPATCH AI  |  Source Code Security Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_y(20)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, f"Generated by DePatch AI  |  Page {self.page_no()}", align="C")


def _write_bold_inline(pdf, text, line_h=5.5):
    """Writes one paragraph, honoring **bold** and `code` spans inline."""
    text = _sanitize(text)
    tokens = re.split(r"(\*\*.*?\*\*|`[^`]*?`)", text)
    for tok in tokens:
        if not tok:
            continue
        if tok.startswith("**") and tok.endswith("**"):
            pdf.set_font("Helvetica", "B", 10)
            pdf.write(line_h, tok[2:-2])
        elif tok.startswith("`") and tok.endswith("`"):
            pdf.set_font("Courier", "", 9.5)
            pdf.set_text_color(120, 40, 120)
            pdf.write(line_h, tok[1:-1])
            pdf.set_text_color(0, 0, 0)
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.write(line_h, tok)
    pdf.ln(line_h)


def _render_markdown_body(pdf: FPDF, markdown_text: str):
    """Minimal renderer for the specific Markdown subset our LLM prompts
    request: ## / ### headers, ```lang code fences, - bullet points,
    **bold**, `inline code`, and plain paragraphs."""
    in_code = False
    code_lines = []

    def flush_code():
        if not code_lines:
            return
        pdf.set_fill_color(*CODE_BG)
        pdf.set_text_color(*CODE_FG)
        pdf.set_font("Courier", "", 9)
        block = _sanitize("\n".join(code_lines))
        pdf.multi_cell(0, 5, block, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)
        code_lines.clear()

    for raw_line in markdown_text.splitlines():
        line = raw_line.rstrip()

        if line.strip().startswith("```"):
            if in_code:
                flush_code()
                in_code = False
            else:
                in_code = True
            continue

        if in_code:
            code_lines.append(line)
            continue

        if not line.strip():
            pdf.ln(2)
            continue

        if line.startswith("## "):
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(*PURPLE)
            pdf.cell(0, 8, _sanitize(line[3:].strip()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_draw_color(*PURPLE)
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
            pdf.ln(3)
            pdf.set_text_color(0, 0, 0)
            continue

        if line.startswith("### "):
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*NAVY)
            pdf.cell(0, 7, _sanitize(line[4:].strip()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_text_color(0, 0, 0)
            continue

        if line.strip().startswith(("- ", "* ")):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_x(pdf.l_margin + 4)
            pdf.write(5.5, "-  ")
            _write_bold_inline(pdf, line.strip()[2:].strip())
            continue

        _write_bold_inline(pdf, line.strip())

    flush_code()


def generate_pdf_report(file_name: str, findings_list: list, report_text: str,
                         report_source: str, output_dir: str = "reports") -> str:
    """Builds the full PDF (summary table + per-function findings + LLM
    report) and returns the saved file path."""
    os.makedirs(output_dir, exist_ok=True)

    pdf = DePatchPDF()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 10, _sanitize(file_name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*GRAY)
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 6, f"Scanned: {ts}   |   Report source: {report_source}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # --- Summary table ---
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(*NAVY)
    pdf.set_text_color(255, 255, 255)
    col_w = [80, 45, 45]
    for w, h in zip(col_w, ["Function", "Verdict", "Confidence"]):
        pdf.cell(w, 8, h, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 10)
    for f in findings_list:
        vulnerable = f["label"] == 1
        pdf.set_text_color(0, 0, 0)
        pdf.cell(col_w[0], 8, _sanitize(f["function_name"][:40]), border=1)
        if vulnerable:
            pdf.set_fill_color(*RED)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(col_w[1], 8, "VULNERABLE", border=1, fill=True, align="C")
        else:
            pdf.set_fill_color(*GREEN)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(col_w[1], 8, "SAFE", border=1, fill=True, align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.cell(col_w[2], 8, f"{f['confidence']:.2f}%", border=1, align="C")
        pdf.ln()
    pdf.ln(6)

    # --- Per-function attended lines ---
    for f in findings_list:
        if not f.get("top_lines"):
            continue
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*NAVY)
        pdf.cell(0, 7, _sanitize(f"Attention-ranked lines -- {f['function_name']}"),
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Courier", "", 8.5)
        for ln, score, snippet in f["top_lines"]:
            pdf.set_fill_color(*LIGHT_GRAY)
            text = _sanitize(f"L{ln:>4}  [{score:.2f}]  {snippet}"[:110])
            pdf.multi_cell(0, 5, text, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3)

    # --- LLM-generated report body ---
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 9, "Security Audit Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)
    _render_markdown_body(pdf, report_text)

    safe_stub = re.sub(r"[^A-Za-z0-9_.-]", "_", file_name)
    out_path = os.path.join(
        output_dir,
        f"depatch_report_{safe_stub}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
    )
    pdf.output(out_path)
    return out_path
